# -*- coding: utf-8 -*-
"""聚宽 jqdata 平台 API 的静态占位（PEP 561 类型存根，仅编辑器/类型检查器用）。

作用：解析 research/ 平台脚本的 `from jqdata import *`，让 Pylance/pyright/mypy
不再报 unresolved import / undefined name。**不是运行时实现**——.pyi 不可被
import，本地直接跑平台脚本仍会 ImportError（防误跑，是特性）。

- 本地测试运行时：tests/jq_fake.py（sys.modules 注入的可执行桩）；
- 真实现：只在聚宽环境；本目录不随脚本上传平台。
"""

from typing import Any, Callable, Optional, Sequence, Union

# ── 平台全局对象 ──────────────────────────────────────────────────
g: Any                                    # 平台全局命名空间（脚本自定义状态挂这里）
log: Any                                  # log.info / log.set_level / log.warn...

# ── 行情 ─────────────────────────────────────────────────────────
def history(count: int, unit: str = '1d', field: str = 'close',
            security_list: Optional[Sequence[str]] = None, df: bool = True,
            skip_paused: bool = False, fq: str = 'pre') -> Any: ...
def attribute_history(code: str, count: int, unit: str = '1d',
                      fields: Sequence[str] = ('close',), skip_paused: bool = True,
                      df: bool = True, fq: str = 'pre') -> Any: ...
def get_price(security: Union[str, Sequence[str]], start_date: Any = None,
              end_date: Any = None, frequency: str = 'daily',
              fields: Optional[Sequence[str]] = None, skip_paused: bool = False,
              fq: str = 'pre', count: Optional[int] = None,
              panel: bool = True, **kw: Any) -> Any: ...
def get_bars(security: str, count: int, unit: str = '1d',
             fields: Sequence[str] = ('date', 'open', 'high', 'low', 'close'),
             include_now: bool = False, end_dt: Any = None,
             fq_ref_date: Any = None, df: bool = True) -> Any: ...
def get_current_data() -> Any: ...
def get_trade_days(start_date: Any = None, end_date: Any = None,
                   count: Optional[int] = None) -> Any: ...
def get_trade_dates(start_date: Any = None, end_date: Any = None) -> Any: ...

# ── 证券与基本面 ─────────────────────────────────────────────────
def get_all_securities(types: Union[str, Sequence[str]],
                       date: Any = None) -> Any: ...
def get_security_info(code: str, date: Any = None) -> Any: ...
def get_fundamentals(q: Any, date: Any = None, statDate: Any = None) -> Any: ...
def query(*args: Any, **kwargs: Any) -> Any: ...
indicator: Any                            # 财务指标表（roe / inc_net_profit_year_on_year ...）
valuation: Any                            # 估值表（pe_ratio / pb_ratio / ...）
income: Any
balance: Any
cashflow: Any
def get_extras(field: Union[str, Sequence[str]], security_list: Sequence[str],
               start_date: Any = None, end_date: Any = None, df: bool = True,
               count: Optional[int] = None) -> Any: ...
def get_locked_shares(stock_list: Sequence[str], start_date: Any,
                      end_date: Any = None,
                      forward_count: Optional[int] = None) -> Any: ...

# ── 下单与撮合 ───────────────────────────────────────────────────
def order(code: str, amount: int, style: Any = None, side: str = 'long',
          close_today: bool = False) -> Any: ...
def order_target(code: str, amount: int, style: Any = None,
                 side: str = 'long', close_today: bool = False) -> Any: ...
def order_value(code: str, value: float, style: Any = None,
                side: str = 'long', close_today: bool = False) -> Any: ...
def order_target_value(code: str, value: float, style: Any = None,
                       side: str = 'long', close_today: bool = False) -> Any: ...
def cancel_order(order: Any) -> None: ...
def get_open_orders() -> Any: ...

class PriceRelatedSlippage:
    def __init__(self, value: float) -> None: ...

def record(**kwargs: Any) -> None: ...

class OrderCost:
    def __init__(self, open_tax: float = 0, close_tax: float = 0,
                 open_commission: float = 0, close_commission: float = 0,
                 min_commission: float = 0, type: str = 'stock',
                 tax_type: str = 'stock') -> None: ...

def set_order_cost(cost: OrderCost, type: str = 'stock',
                   ref: Any = None) -> None: ...
def set_option(name: str, value: Any) -> None: ...
def set_benchmark(security: str) -> None: ...
def set_slippage(s: Any) -> None: ...
def set_universe(universe: Sequence[str]) -> None: ...

# ── 调度 ─────────────────────────────────────────────────────────
def run_daily(func: Callable[..., Any], time: Any = '9:30',
              reference_security: str = '000300.XSHG') -> None: ...
def run_weekly(func: Callable[..., Any], weekday: Any = 1,
               time: Any = '9:30', reference_security: str = '000300.XSHG') -> None: ...
def run_monthly(func: Callable[..., Any], monthday: Any = 1,
                time: Any = '9:30', reference_security: str = '000300.XSHG') -> None: ...

# initialize(context) / on_strategy_end(context) 等为脚本自定义钩子，平台回调，不在此声明。
